import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@uswds/uswds/css/uswds.css";
// import "@trussworks/react-uswds/lib/uswds.css";
// import "@trussworks/react-uswds/lib/index.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Box, Container, ThemeProvider } from "@mui/material";
import theme from "./theme";
import { NavBar } from "@/components/Navbar";
import { MainContent } from "@/components/MainContent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AppRouterCacheProvider>
					<ThemeProvider theme={theme}>
						<NavBar />
						<Container>
							<MainContent>{children}</MainContent>
						</Container>
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
